Pida/local/urls.py
/home/lord-sarcastic/Pida/Pida/urls.py

Pida/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('main.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views, forms
app_name = 'main'
urlpatterns = [
    path('sign-in', views.SignInView.as_view(), name='signin'),
    path('', views.SignInView.as_view(), name='signin'),
    path('sign-up', views.SignUpView.as_view(), name='signup'),
    path('secure-digit/', views.MainView.as_view(), name='main'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class Key(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    digit = models.CharField(max_length=1024, blank=True)
    start = models.IntegerField()
    end = models.IntegerField()

    def __str__(self):
        return f'{self.username}'

    def clean(self, *args, **kwargs):
        if self.end <= self.start:
            raise ValidationError(_("Start value should be less than end value"))
        return super().clean(*args, **kwargs)

main/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from .models import Key
    
class CreateUserForm(ModelForm):
    confirm_password = forms.CharField()
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password', 'confirm_password',)
#        labels = {
#            'username' : _('Username:'),
#            'first_name' : _('First name:'),
#            'last_name' : _('Last name:'),
#            'email' : _('Email:'),
#            'password' : _('Enter password:'),
#        }
#        help_texts = {
#            'username' : _('This name will be visible when you make a post'),
#            'first_name' : _('JOHN doe'),
#            'last_name' : _('john DOE'),
#        }
#        widgets = {
#            'username' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Username'}),
#            'first_name' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'First name'}),
#            'last_name' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Last name'}),
#            'email' : forms.EmailInput(attrs={'class' : 'form-control', 'placeholder' : 'Email'}),
#            'password' : forms.PasswordInput(attrs={'class' : 'form-control', 'placeholder' : 'Password'}),
#        }

#407
class SecureKeyForm(ModelForm):
    password = forms.CharField()
    confirm_digit = forms.CharField()
    class Meta:
        model = Key
        fields = ('digit', 'start', 'end','confirm_digit','password',)
        
class UserLoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        labels = {
            'username' : _('Username'),
            'password' : _('Password'),
        }

main/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.views import generic, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse, reverse_lazy
from django.db.models import Q, F, Count
from .models import Key
from .forms import *

class SignUpView(View):
    template_name = 'main/signup.html'
    
    def get_queryset(self):
        return User.objects.all()
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        form = CreateUserForm(request.POST)
#        if form.is_valid():
        if form['password'].data != form['confirm_password'].data:
            return render(request, self.template_name, {'warning' : 'Passwords do not match.'})

        if len(form['password'].data) < 8:
            return render(request, self.template_name, {'warning' : 'Password too short, should not be less than 8 characters.'})

        try:
            user = User.objects.get(username=form['username'].data.lower())
            return render(request, self.template_name, {'warning' : 'Username already exists.'})
        except User.DoesNotExist:
            user = User.objects.create_user(form['username'].data.lower(), email=form['email'].data, password=form['password'].data, first_name=form['first_name'].data.capitalize(), last_name=form['last_name'].data.lower())
        user = authenticate(username=user.username, password=form['password'].data)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/secure-digit/')
        else:
            return HttpResponse("<h1>This user is not yet authenticated, contact the admin for more information or create a new account</h1>")
#        else:
#            return render(request, self.template_name, {'warning' : f"Form not valid!{form['username'].data.lower()}: {form['email'].data} : {form['password'].data}: {form['first_name'].data} : {form['last_name'].data}: {form['confirm_password'].data}"})
    
    
class SignInView(View):
    template_name = 'main/signin.html'
    
    def get_queryset(self):
        return User.objects.all()
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        form = UserLoginForm(request.POST)
#        if form.is_valid():
        try:
            user = User.objects.get(username=form['username'].data.lower())
            if user.check_password(form['password'].data):
                user = authenticate(username=user.username, password=form['password'].data)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect('/secure-digit/')
                else:
                    return HttpResponse("<h1>This user is not yet authenticated, contact the admin for more information or create a new account</h1>")
            else:
                return render(request, self.template_name, {'warning' : 'Wrong password!'})
        except User.DoesNotExist:
            return render(request, self.template_name, {'warning' : 'User does not exist.'})
#        else:
#            return render(request, self.template_name, {'warning' : f"Form not valid!"})
            
        
class MainView(LoginRequiredMixin, View):
    login_url = '/'
    template_name = 'main/main.html'
    
    def get_queryset(self):
        return User.objects.all()
    
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
    def post(self, request, *args, **kwargs):
        form = SecureKeyForm(request.POST)
#        if form.is_valid():
        if request.user.check_password(form['password'].data):
            if form['digit'].data == form['confirm_digit'].data:
                if form['end'].data < form['start'].data:
                    return render(request, self.template_name, {'warning' : 'Start value should be less than end value!'})
                key = Key(user=request.user, digit=form['digit'].data, start=form['start'].data, end=form['end'].data)
                key.save()
                return render(request, 'success.html')
            else:
                return render(request, self.template_name, {'warning' : 'Digits do not match!'})
        else:
            return render(request, self.template_name, {'warning' : 'Wrong password!'})
#        else:
#            return render(request, self.template_name, {'warning' : f"Form not valid!{form['username'].data.lower()}: {form['email'].data} : {form['password'].data}: {form['first_name'].data} : {form['last_name'].data}: {form['confirm_password'].data}"})

templates/main/main.html
<!--
Author: 

-->

<!DOCTYPE html>
<html lang="zxx">

<head>
    {% load static %}
    <title></title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords" content=" " />
    <!-- //Meta tag Keywords -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" /><!-- Style-CSS -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet"><!-- font-awesome-icons -->
</head>

<body>
    <section class="signin-form">
        <div class="overlay">
            <div class="wrapper">

                <div class="mainbody">
                    <h4 class="form-head" align="center">Enter the password you wish to secure</h4>
                    <p class="form-para"></p>
                    <div class="main-div">
       
                    </div>
                    <div class="form-34or">
                        <span class="pros">
                            <span>Password Delay Intelligence Algorithm</span>
                        </span>
                    </div>
                    <form action="{% url 'main:main' %}" method="post">
                        {% csrf_token %}
                        <div class="">
                            <p style="color: red; font-size: 1rem;">{{ warning }}</p>
                        </div>
                        <div class="">
                            <p class="text-head">Password</p>
                            <input type="password" name="password" id="id_password" class="input" placeholder="" required="" />
                        </div>

                        <div class="">
                            <p class="text-head">Secured Digit Password</p>
                            <input type="password" name="digit" id="id_digit" class="input" placeholder="" required="" />
                        </div>

                        <div class="">
                            <p class="text-head">Confirm Secured Digit Password</p>
                            <input type="password" name="confirm_digit" id="id_confirm_digit" class="input" placeholder="" required="" />
                        </div>
                        <div class="delaybox">
                            <p class="text-head" align="center">Set Delay</p>
                            <div class="inline">
                            <select name="start" id="id_start">
                                <option value="0">0</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                                <option value="6">6</option>
                                <option value="7">7</option>
                                <option value="8">8</option>
                                <option value="9">9</option>
                              </select> 
                            </div>
                            <div class="inline">
                                <select name="end" id="id_end">
                                    <option value="0">0</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>                                  
                                </select> 
                            </div>
                        </div>
                        <button type="submit" class="signinbutton btn">Secure Digit</button>
                    </form>
                </div>
            </div>
            <!-- copyright -->
		<div class="copyright text-center">
                <p>© 2019  PDA . All rights reserved | </p>
            </div>
            <!-- //copyright --> 
        </div>
    </section>
</body>

</html>

templates/main/signin.html
<!--
Author: W3layouts

-->

<!DOCTYPE html>
<html lang="zxx">

<head>
    {% load static %}
    <title></title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords" content=" " />
    <!-- //Meta tag Keywords -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" /><!-- Style-CSS -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet"><!-- font-awesome-icons -->
</head>

<body>
    <section class="signin-form">
        <div class="overlay">
            <div class="wrapper">
                <div class="logo text-center top-bottom-gap">
                    <a class="brand-logo" href="#">PDA Signin Form</a>
                    <!-- if logo is image enable this   
			<a class="brand-logo" href="#index.html">
			    <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
			</a> -->
                </div>
                <div class="form34">
                    <h4 class="form-head">Sign in now</h4>
                    <p class="form-para"></p>
                    <div class="main-div">
                    <!--    <a href="#facebook">
                            <div class="signin facebook">
                                <span class="fa fa-facebook" aria-hidden="true"></span>
                                <p class="action">facebook</p>
                            </div>
                        </a>
                        <a href="#google-plus">
                            <div class="signin google-plus">
                                <span class="fa fa-google-plus" aria-hidden="true"></span>
                                <p class="action">google</p>
                            </div>
                        </a>-->
                    </div>
                    <div class="form-34or">
                        <span class="pros">
                            <span>Password Delay Intelligence Algrothm</span>
                        </span>
                    </div>
                    <form action="{% url 'main:signin' %}" method="post">
                        {% csrf_token %}
                        <div class="">
                            <p style="color: red; font-size: 1rem;">{{ warning }}</p>
                        </div>
                        <div class="">
                            <p class="text-head">Username</p>
                            <input type="text" name="username" id="id_username" class="input" placeholder="" required="" />
                        </div>
                        <div class="">
                            <p class="text-head">Password</p>
                            <input type="password" name="password" id="id_password" class="input" placeholder="" required="" />
                        </div>
<!--
                        <label class="remember">
                            <input type="checkbox">
                            <span class="checkmark"></span>Remember me
                        </label>
-->
                        <button type="submit" class="signinbutton btn">Sign in</button>
                        <p class="signup">Have not an account yet?<a href="{% url 'main:signup' %}" class="signuplink">Sign up</a>
                        </p>
                    </form>
                </div>
            </div>
            <!-- copyright -->
		<div class="copyright text-center">
                <p>© 2019  Signin Form . All rights reserved | </p>
            </div>
            <!-- //copyright --> 
        </div>
    </section>
</body>

</html>

templates/main/signup.html
<!--
Author: 

-->

<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <title></title>
    <!-- Meta tag Keywords -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8" />
    <meta name="keywords" content=" " />
    <!-- //Meta tag Keywords -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" /><!-- Style-CSS -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet"><!-- font-awesome-icons -->
</head>

<body>
    <section class="signin-form">
        <div class="overlay">
            <div class="wrapper">
                <div class="logo text-center top-bottom-gap">
                    <a class="brand-logo" href="index.html">PDA Signup Form</a>
                    <!-- if logo is image enable this   
			<a class="brand-logo" href="#index.html">
			    <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
			</a> -->
                </div>
                <div class="form34">
                    <h4 class="form-head">Signup now</h4>
                    <p class="form-para"></p>
                    <div class="main-div">
                    <!--    <a href="#facebook">
                            <div class="signin facebook">
                                <span class="fa fa-facebook" aria-hidden="true"></span>
                                <p class="action">facebook</p>
                            </div>
                        </a>
                        <a href="#google-plus">
                            <div class="signin google-plus">
                                <span class="fa fa-google-plus" aria-hidden="true"></span>
                                <p class="action">google</p>
                            </div>
                        </a>-->
                    </div>
                    <div class="form-34or">
                        <span class="pros">
                            <span>Password Delay Intelligence Algorithm</span>
                        </span>
                    </div>
                    <form action="{% url 'main:signup' %}" method="post">
                        {% csrf_token %}
                        <div class="">
                            <p style="color: red; font-size: 1rem;">{{ warning }}</p>
                        </div>
                        <div class="">
                            <p class="text-head">First Name</p>
                            <input type="text" name="first_name" id="id_first_name" class="input" placeholder="Enter full name here" required="" />
                        </div>
                        <div class="">
                            <p class="text-head">Last Name</p>
                            <input type="text" name="last_name" id="id_last_name" class="input" placeholder="Enter full name here" required="" />
                        </div>
                        <div class="">
                            <p class="text-head">Email Address</p>
                            <input type="email" name="email" id="id_email" class="input" placeholder="Enter email" required="" />
                        </div>
                        
                        <div class="">
                            <p class="text-head">Username</p>
                            <input type="text" name="username" id="id_username" class="input" placeholder="" required="" />
                        </div>
                        <div class="">
                            <p class="text-head">Password</p>
                            <input type="password" name="password" id="id_password" class="input" placeholder="" required="" />
                        </div>
                        <div class="">
                            <p class="text-head">Confirm Password</p>
                            <input type="password" name="confirm_password" id="id_confirm_password" class="input" placeholder="" required="" />
                        </div>
<!--
                        <label class="remember">
                            <input type="checkbox">
                            <span class="checkmark"></span>Remember me
                        </label>
-->
                        <button type="submit" class="signinbutton btn" style="color:#ffffff;">Create Account</button>
                    </form>
                    <p class="signup" >I already have an account <a href="{% url 'main:signin' %}" class="signuplink">Sign in</a></p>
                </div>
            </div>
            <!-- copyright -->
		<div class="copyright text-center">
                <p>© 2019  signup Form . All rights reserved | </p>
            </div>
            <!-- //copyright --> 
        </div>
    </section>
</body>

</html>